style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/jeremaihloo/icode
options:
  commits:
    filters:
      Type:
        - Add
        - Update
        - Fix
        - Perf
        - Refactor
  commit_groups:
    title_maps:
      Add: Add Features
      Update: Update
      Fix: Bug Fixes
      Perf: Performance Improvements
      Refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
